### ISSUE TITLE
Feature: Project configuration file system

### ISSUE THREAD

**Issue by robwhite4** [robwhite4/claude-memory#62]
## Feature Description
Implement a comprehensive configuration system using `.claude/config.yml` to allow project-specific customization of claude-memory behavior.

## Problem
Currently, all projects use the same default settings, but teams need:
- Project-specific configurations
- Custom aliases and shortcuts
- Different optimization strategies
- Team-specific workflows

### Configuration File Location
```
.claude/
├── config.yml          # Project configuration
├── config.local.yml    # Local overrides (gitignored)
└── templates/          # Custom templates
```

### Configuration Schema
```yaml
# .claude/config.yml
version: 1.0

project:
  name: ARWA Dashboard
  description: Water system monitoring and analytics
  team: Infrastructure Team
  created: 2025-01-15

memory:
  # Token optimization settings
  optimize:
    maxTokens: 5000
    autoArchive: 90d
    strategies:
      - summarize-old-decisions
      - compress-knowledge
      - archive-completed-tasks
  
  # Git integration
  git:
    enabled: true
    autoCommit: true
    commitMessage: "chore: Update claude memory - {action}"
    includeTimestamp: true
    excludeBranches: ["main", "master"]
    branchSpecific: true  # Use CLAUDE-{branch}.md
  
  # Export settings
  export:
    defaultFormat: json
    defaultTemplate: github-issues
    timestampFormat: ISO8601
    
  # Search defaults
  search:
    caseSensitive: false
    includeArchived: false
    defaultContext: 2

# Command aliases for productivity
aliases:
  # Short aliases
  t+: task add
  t?: task list
  tc: task complete
  k+: knowledge add
  d+: decision
  p+: pattern add
  
  # Complex aliases
  standup: session start "Daily standup"
  endday: session end "Day completed"
  cleanup: task cleanup --older-than 30d

# Interactive mode settings
interactive:
  enabled: true
  prompt: "cmem> "
  history: 1000
  theme: dark
  autoComplete: true
  
# Hooks for automation
hooks:
  post-decision:
    - git add .claude/
    - git commit -m "decision: {decision_title}"
  
  post-task-complete:
    - echo "Task {task_id} completed" >> .claude/completed.log
  
  pre-session-end:
    - claude-memory export --format json --save

# Team settings
team:
  defaultAssignees:
    security: "@security-team"
    frontend: "@frontend-team"
    backend: "@backend-team"
  
  taskPrefixes:
    bug: "🐛"
    feature: "✨"
    chore: "🔧"

# Custom fields for domain-specific needs
custom:
  task:
    fields:
      - name: storyPoints
        type: number
        required: false
      - name: sprint
        type: string
        required: true
  
  pattern:
    categories:
      - security
      - performance
      - architecture
      - testing
```

### Configuration Loading
```javascript
class ConfigManager {
  constructor() {
    this.config = this.loadConfig();
  }
  
  loadConfig() {
    const layers = [
      this.loadDefaults(),
      this.loadProjectConfig(),
      this.loadLocalConfig(),
      this.loadEnvOverrides()
    ];
    
    return deepMerge(...layers);
  }
  
  loadProjectConfig() {
    const configPath = path.join('.claude', 'config.yml');
    if (fs.existsSync(configPath)) {
      return yaml.load(fs.readFileSync(configPath));
    }
    return {};
  }
  
  get(key, defaultValue) {
    return _.get(this.config, key, defaultValue);
  }
}
```

### CLI Integration
```bash
# Show current config
claude-memory config show

# Get specific value
claude-memory config get memory.optimize.maxTokens

# Set value
claude-memory config set memory.optimize.maxTokens 6000

# Validate config
claude-memory config validate

# Init with template
claude-memory init --template enterprise
```

### Alias Expansion
```javascript
function expandAlias(command, config) {
  const aliases = config.get('aliases', {});
  
  // Direct alias
  if (aliases[command]) {
    return aliases[command];
  }
  
  // Partial match for complex commands
  const parts = command.split(' ');
  if (aliases[parts[0]]) {
    return aliases[parts[0]] + ' ' + parts.slice(1).join(' ');
  }
  
  return command;
}
```

### Hook System
```javascript
async function runHooks(hookName, context) {
  const hooks = config.get(`hooks.${hookName}`, []);
  
  for (const hook of hooks) {
    const command = interpolate(hook, context);
    await exec(command);
  }
}

// Usage
await runHooks('post-decision', {
  decision_title: 'Use PostgreSQL for database',
  decision_id: 'abc123'
});
```

### Environment Variables
```bash
# Override config via environment
CLAUDE_MEMORY_MAX_TOKENS=6000 claude-memory optimize
CLAUDE_MEMORY_GIT_AUTO_COMMIT=false claude-memory decision "..."
```

### Config Templates
```bash
# Starter templates
claude-memory init --list-templates
Available templates:
- default: Basic configuration
- enterprise: Full-featured with team settings
- minimal: Bare minimum setup
- agile: Scrum/sprint focused

# Use template
claude-memory init --template enterprise
```

### Team Synchronization
```yaml
# Team shared config (version controlled)
extends: https://github.com/company/claude-configs/base.yml

# Local overrides
memory:
  git:
    autoCommit: false  # Override team default
```

## Benefits
- Customizable per-project workflows
- Team standardization
- Reduced repetitive typing via aliases
- Automation through hooks
- Flexible configuration layers

### Security Team Config
```yaml
aliases:
  vuln+: pattern add --priority high --category security
  secreview: task add --assignee @security-team --tag security-review

hooks:
  post-pattern:
    - ./scripts/notify-security-team.sh "{pattern_id}"
```

### Solo Developer Config
```yaml
memory:
  optimize:
    maxTokens: 3000  # Smaller context for faster responses
    
aliases:
  morning:  < /dev/null | 
    session start "Morning" && 
    task list pending &&
    pattern list unresolved
```

## Related
- Part of comprehensive feedback from Rob White IV
- Enables team collaboration
- Foundation for advanced features
