### ISSUE TITLE
Feature: Project templates for common setups

### ISSUE THREAD

**Issue by robwhite4** [robwhite4/claude-memory#69]
## Feature Description
Provide pre-configured project templates for common development scenarios to help users get started quickly with best practices.

## Problem
Users starting new projects need to:
- Configure claude-memory from scratch
- Determine optimal settings for their project type
- Set up common patterns and knowledge items
- Create initial task structures

### Template Commands
```bash
# List available templates
claude-memory init --list-templates

# Initialize with template
claude-memory init --template web-app
claude-memory init --template api-service
claude-memory init --template open-source

# Create custom template from current project
claude-memory template create my-template
claude-memory template export my-template.json
```

#### 1. Web Application Template
```yaml
# .claude/templates/web-app.yml
name: Web Application
description: Full-stack web application with modern framework
config:
  project:
    type: web-application
    stack: frontend-backend
  
  aliases:
    comp+: task add --tag component
    bug+: task add --priority high --tag bug
    feat+: task add --tag feature
    
  memory:
    optimize:
      maxTokens: 5000
      
knowledge:
  - key: framework
    value: "React/Vue/Angular (to be decided)"
    category: technical
  - key: styling
    value: "CSS-in-JS/Tailwind (to be decided)"
    category: technical
  - key: state_management
    value: "Context/Redux/Zustand (to be decided)"
    category: technical
    
patterns:
  - pattern: "Component rendering performance"
    description: "Optimize re-renders and memo usage"
    priority: high
  - pattern: "Bundle size optimization"
    description: "Keep JavaScript bundle under 200KB"
    priority: medium
    
tasks:
  - description: "Set up development environment"
    priority: high
  - description: "Choose and configure framework"
    priority: high
  - description: "Set up CI/CD pipeline"
    priority: medium
  - description: "Configure linting and formatting"
    priority: medium
```

#### 2. API Service Template
```yaml
name: API Service
description: RESTful API or microservice
config:
  project:
    type: api-service
    
  aliases:
    endpoint+: task add --tag api-endpoint
    schema+: knowledge add --category database
    
knowledge:
  - key: api_version
    value: "v1"
    category: config
  - key: database_type
    value: "PostgreSQL/MongoDB (to be decided)"
    category: technical
  - key: auth_strategy
    value: "JWT/OAuth2 (to be decided)"
    category: security
    
patterns:
  - pattern: "API versioning strategy"
    description: "Maintain backward compatibility"
    priority: high
  - pattern: "Rate limiting implementation"
    description: "Prevent API abuse"
    priority: high
  - pattern: "Database query optimization"
    description: "N+1 queries and indexing"
    priority: medium
    
tasks:
  - description: "Design API schema"
    priority: high
  - description: "Set up database migrations"
    priority: high
  - description: "Implement authentication"
    priority: high
  - description: "Add API documentation"
    priority: medium
```

#### 3. Open Source Project Template
```yaml
name: Open Source Project
description: Community-driven open source project
config:
  project:
    type: open-source
    
  git:
    autoCommit: false  # Let contributors control commits
    
  aliases:
    issue+: task add --tag github-issue
    pr+: task add --tag pull-request
    
knowledge:
  - key: contributing_guide
    value: "CONTRIBUTING.md"
    category: documentation
  - key: code_of_conduct
    value: "CODE_OF_CONDUCT.md"
    category: documentation
  - key: license
    value: "MIT/Apache-2.0 (to be decided)"
    category: legal
    
patterns:
  - pattern: "First-time contributor experience"
    description: "Make onboarding smooth"
    priority: high
  - pattern: "PR review turnaround"
    description: "Respond within 48 hours"
    priority: high
    
tasks:
  - description: "Create CONTRIBUTING.md"
    priority: high
  - description: "Set up issue templates"
    priority: high
  - description: "Configure CI for PRs"
    priority: high
  - description: "Add good first issue labels"
    priority: medium
```

#### 4. Data Science Template
```yaml
name: Data Science Project
description: ML/AI research or analysis project
config:
  aliases:
    exp+: knowledge add --category experiments
    data+: knowledge add --category datasets
    model+: pattern add --tag model-architecture
    
knowledge:
  - key: dataset_source
    value: "TBD"
    category: datasets
  - key: target_metric
    value: "accuracy/F1/AUC (to be decided)"
    category: experiments
    
patterns:
  - pattern: "Data leakage prevention"
    description: "Ensure proper train/test split"
    priority: high
  - pattern: "Reproducibility"
    description: "Set random seeds, log versions"
    priority: high
```

### Template Application Logic
```javascript
async function applyTemplate(templateName) {
  const template = await loadTemplate(templateName);
  
  // 1. Create config
  await writeConfig(template.config);
  
  // 2. Add knowledge items
  for (const item of template.knowledge || []) {
    await exec(`claude-memory knowledge add "${item.key}" "${item.value}" --category ${item.category}`);
  }
  
  // 3. Add patterns
  for (const pattern of template.patterns || []) {
    await exec(`claude-memory pattern add "${pattern.pattern}" "${pattern.description}" --priority ${pattern.priority}`);
  }
  
  // 4. Add initial tasks
  for (const task of template.tasks || []) {
    await exec(`claude-memory task add "${task.description}" --priority ${task.priority}`);
  }
  
  // 5. Create suggested structure
  if (template.structure) {
    await createProjectStructure(template.structure);
  }
}
```

### Custom Template Creation
```javascript
async function createTemplate(name) {
  const currentState = {
    config: await loadConfig(),
    knowledge: await getRecentKnowledge(10),
    patterns: await getTopPatterns(5),
    tasks: await getTemplateTasks()
  };
  
  // Interactive template builder
  const template = await buildTemplate(currentState);
  
  // Save to templates directory
  await saveTemplate(name, template);
  
  console.log(`✅ Template '${name}' created`);
  console.log(`Share it: claude-memory template export ${name}`);
}
```

### Template Marketplace
```bash
# Install community template
claude-memory template install https://github.com/user/claude-memory-template-nextjs

# Browse templates
claude-memory template browse --tag web-dev

# Rate template
claude-memory template rate nextjs-template 5
```

### Smart Template Selection
```javascript
async function suggestTemplate() {
  const indicators = await detectProjectType();
  
  const scores = {};
  for (const [name, template] of Object.entries(templates)) {
    scores[name] = calculateMatchScore(indicators, template);
  }
  
  const best = Object.entries(scores)
    .sort(([,a], [,b]) => b - a)
    .slice(0, 3);
    
  console.log('📋 Suggested templates based on your project:');
  best.forEach(([name, score]) => {
    console.log(`  - ${name} (${Math.round(score * 100)}% match)`);
  });
}
```

## Benefits
- Quick project initialization
- Best practices built-in
- Consistent team setups
- Reduced decision fatigue
- Community sharing

## Success Metrics
- Time to productive use
- Template usage rate
- Community templates created
- User satisfaction

## Related
- Works with setup wizard (#68)
- Part of onboarding improvements
- Enables team standardization
