### ISSUE TITLE
Fix: Clean up npm install warnings about funding and vulnerabilities

### ISSUE THREAD

**Issue by robwhite4** [robwhite4/claude-memory#71]
## Problem Description
When installing claude-memory, users see npm warnings that create a poor first impression and raise unnecessary concerns.

## Current Warnings
```bash
$ npm install -g claude-memory

npm WARN deprecated inflight@1.0.6: This module is not supported
npm WARN deprecated glob@7.2.3: Glob versions prior to 9 are no longer supported
npm WARN funding: claude-memory@1.10.3: Package has funding information but no 'fund' command

3 vulnerabilities (2 moderate, 1 high)
```

## User Impact
- Creates doubt about package quality
- Raises security concerns
- Clutters installation output
- Poor first impression

### 1. Update Dependencies
```json
// package.json - Update outdated dependencies
{
  "dependencies": {
    "glob": "^10.3.0",  // Update from 7.x
    "chalk": "^5.3.0",  // Update from 4.x
    // Remove deprecated packages
    // Update all dependencies to latest stable
  }
}
```

### 2. Run Security Audit
```bash
# Fix vulnerabilities
npm audit
npm audit fix

# For breaking changes
npm audit fix --force  # Careful review needed

# Document any that can't be fixed
```

### 3. Add Funding Configuration
```json
// package.json
{
  "funding": {
    "type": "github",
    "url": "https://github.com/sponsors/robwhite4"
  }
}
```

Or remove funding field if not needed:
```json
{
  // Remove "funding" field entirely
}
```

### 4. Add npm Ignore for Unnecessary Files
```
# .npmignore
.github/
docs/
tests/
*.test.js
.env.example
CONTRIBUTING.md
```

### 5. Dependency Hygiene
```javascript
// scripts/check-deps.js
const depcheck = require('depcheck');

async function checkDependencies() {
  const unused = await depcheck('.', {});
  
  console.log('Unused dependencies:', unused.dependencies);
  console.log('Unused devDependencies:', unused.devDependencies);
  
  // Remove unused
  // Update outdated
  // Check for security issues
}
```

### 6. Pre-publish Checklist
```bash
# Before each release
npm audit
npm outdated
npm run test
npm run lint
npm pack --dry-run  # Check package contents
```

## Implementation Steps
1. Audit current dependencies
2. Update all outdated packages
3. Fix security vulnerabilities
4. Remove unused dependencies
5. Configure or remove funding field
6. Test thoroughly after updates
7. Add CI check for vulnerabilities

## Testing After Updates
```bash
# Local testing
npm link
claude-memory --version
claude-memory task add "Test after updates"

# Clean install test
npm uninstall -g claude-memory
npm cache clean --force
npm install -g claude-memory
```

## CI Integration
```yaml
# .github/workflows/security.yml
name: Security Check
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level=moderate
        
      - name: Check for outdated
        run: npm outdated || true
```

## Long-term Maintenance
- Regular dependency updates (monthly)
- Automated security scanning
- Dependabot configuration
- Clear security policy

## Benefits
- Clean installation experience
- Improved security posture
- Better first impression
- Reduced support questions
- Professional package presentation

## Priority
Low - But affects every new user's experience

## Related
- Part of comprehensive feedback from Rob White IV
- Improves onboarding experience
- Professional package maintenance
